#!/bin/sh
RED='\033[0;31m'
NC='\033[0m'

branch_name=$(git rev-parse --abbrev-ref HEAD)

case "$branch_name" in
  develop|main)
    echo "${RED}Pushing to '${branch_name}' is not allowed! Please create a merge request.${NC}"
    exit 1
    ;;
esac

echo "Push is allowed, continuing..."
